export const GET_POKEMON = 'GET_POKEMON';
export const LIST_POKEMON = 'LIST_POKEMON';
export const ADD_POKEMON = 'ADD_POKEMON';
export const ALL_POKEMONS = 'ALL_POKEMONS';
export const RESTART_PROFILE = 'RESTART_PROFILE';
